# Generated by Django 2.2 on 2019-04-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190416_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_register',
        ),
    ]
